### ISSUE TITLE
Automation fails in zyn-fusion ("Unknown special key 57344")

### ISSUE THREAD

**Issue by JohannesLorenz** [JohannesLorenz/lmms-zyn-fusion-test#2]
Reported in #1 by @Bleuzen:

Pressing F1 and left mouse button on a control, as soon as moving the mouse Zyn GUI crashes / closes. Console out:
```
z.zest_dnd_drop = (nil)
z.zest_dnd_pick = (nil)
z.zest_script = (nil)
z.zest_get_remote_url = (nil)
[INFO:Zyn] setup_pugl()
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at /opt/zyn-fusion/
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the developement of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
Time for a fast load is 1.143ms load(0.004) class(0) spawn(1.139)...
making reverse graph[1089]<0.618 ms>
[INFO:Zyn] zest_setup()
[DEBUG:Zyn] setting up animation fps
[INFO] Unknown special key(57344)...
```
It looks like the zest app uses an old libzest, rather than the one this project delivers.
Does your `LD_LIBRARY_PATH` maybe contain directories where other versions of zest are (`echo $LD_LIBRARY_PATH`)? If yes, please don't change it, this is an interesting test which I could fix.

For the future, a compatibility check of the app and its library would be good to prevent mismatches.

**Comment by JohannesLorenz** [comment]
I just pushed 1efbf5e . If you pull this repo and re-run the build script, maybe it's already fixed?

**Comment by Bleuzen** [comment]
No it's not. Still same error.

**Comment by JohannesLorenz** [comment]
What's your `$LD_LIBRARY_PATH`? Also, what does `xargs --null --max-args=1 < /proc/$(pidof zyn-fusion)/environ  | grep LD_` say?

**Comment by Bleuzen** [comment]
My `$LD_LIBRARY_PATH` is empty.
Output of the command:
`LD_LIBRARY_PATH=/mnt/.../lmms-zyn-fusion-test/mruby-zest-build/package`
(I replaced a part of the path with "...")

**Comment by JohannesLorenz** [comment]
Does it still say `Found Assets at /opt/zyn-fusion/` ?
What happens if you temporary go root and `mv /opt/zyn-fusion /opt/zyn-fusion-bak`?

**Comment by Bleuzen** [comment]
Yes, it still said that Found Assets.

I renamed my zyn-fusion directory and now it works.
Renamed it back (without the "-bak" prefix again) and it crashes.
So it has something to do with my existing zyn fusion install.

**Comment by JohannesLorenz** [comment]
OK, can you please pull once more (ea12727) and build again? I hope it works now.

**Comment by Bleuzen** [comment]
Yes it works now! :)
